# Numpy 
NumPy is a python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.

# What is an array 
An array is a data structure that stores values of same data type .In Python main difference between arrays and lists is that list contain values corresponding to different data types while as python only contains values corresponding to same data type 

In [1]:
## Initially Let us import numpy 
import numpy as np 

In [2]:
## Creating a one dimensional array
my_lst=[1,2,3,4]
arr=np.array(my_lst)

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr

array([1, 2, 3, 4])

In [5]:
## arr.shape tells you number of rows and columns
arr.shape

(4,)

In [16]:
## Cereating a multi dimensional array
my_lst1=[1,2,3,4,5]
my_lst2=[5,4,3,2,1]
my_lst3=[6,7,8,9,10]
arr=np.array([my_lst1,my_lst2,my_lst3])

In [7]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 5,  4,  3,  2,  1],
       [ 6,  7,  8,  9, 10]])

In [11]:
arr.shape

(3, 5)

In [8]:
## Reshaping the two dimensional array  by following function
arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  5],
       [ 4,  3,  2],
       [ 1,  6,  7],
       [ 8,  9, 10]])

In [9]:
## check the shape of an array 
arr.shape

(3, 5)

# Indexing 

In [29]:
## Accessing the array elements 
arr=np.array([1,2,3,4,5,6,7,8,9])

In [14]:
## Indexing always start with 0 
arr[3]

4

In [15]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
## In Mutli Dimensional array :
arr

array([[ 1,  2,  3,  4,  5],
       [ 5,  4,  3,  2,  1],
       [ 6,  7,  8,  9, 10]])

In [19]:
## The indexing in multi dimensional array wroks lik this 
## It has two components the row index and column index , The indexing start 0 
## Printing first tow rows 
arr[0:2,0:2]

array([[1, 2],
       [5, 4]])

In [20]:
arr[2:4,2:4]

array([[8, 9]])

In [21]:
arr[1:4,2:4]

array([[3, 2],
       [8, 9]])

# Inbuild Functions .


In [23]:
## Creates an one dimensional array between 0 -10
arr=np.arange(0,10)


In [24]:
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
## Creates an one dimensional array between 0 -10 with a gap of 2
arr=np.arange(0,10,step=2)

In [26]:
arr


array([0, 2, 4, 6, 8])

In [28]:
#Return evenly spaced numbers over a specified interval.
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [30]:
## Copy function and broadcasting 
arr


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
## Copy function and broadcasting replaces all the elements from 3 by 100 
arr[3:]=100

In [32]:
arr


array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [33]:
arr1=arr

In [34]:
arr1=arr.copy()

In [37]:
print(arr)
arr1[3:]=1000
print(arr1)

[  1   2   3 100 100 100 100 100 100]
[   1    2    3 1000 1000 1000 1000 1000 1000]


In [36]:
arr


array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [39]:
## Some conditions very useful in exploratory data anlaysis
val=2
arr*2

array([  2,   4,   6, 200, 200, 200, 200, 200, 200])

In [40]:
arr/2

array([ 0.5,  1. ,  1.5, 50. , 50. , 50. , 50. , 50. , 50. ])

In [41]:
arr[arr<2]

array([1])

In [42]:
arr[arr<300]

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [43]:
np.ones(4)

array([1., 1., 1., 1.])

In [44]:
np.ones((2,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [46]:
## random distribution 
##Create an array of the given shape and populate it with random samples from a uniform distribution
np.random.rand(3,3)

array([[0.38452476, 0.68000745, 0.71139361],
       [0.39162224, 0.57377231, 0.03199715],
       [0.75355419, 0.83171402, 0.39281639]])

In [49]:
##Return a sample (or samples) from the "standard normal" distribution.

arr_ex=np.random.randn(4,4)

In [48]:
arr_ex

array([[ 0.04823128,  0.59407664, -0.00768689, -0.69284594],
       [-0.95729009,  0.73351664,  0.11083324, -0.67630069],
       [ 0.01834244,  0.22734587,  0.83929891, -0.57122843],
       [ 0.94437246, -0.31714414,  1.24706183,  1.11791538]])